apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: crossplane-system
type: Opaque
data:
  creds: ${AZURE_CREDENTIALS_BASE64} # You'll need to replace this with your base64 encoded Azure credentials
