---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: "1.18"
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    metrics:
      enabled: true
    resourcesCrossplane:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
    webhooks:
      enabled: true
    provider:
      packages: []
    configuration:
      packages: []
    function:
      packages: []
    rbacManager:
      deploy: true
      skipAggregatedClusterRoles: false
      replicas: 1
      leaderElection: true
    packageCache:
      medium: "Memory"
      sizeLimit: 50Mi
    securityContextCrossplane:
      runAsUser: 65532
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    resourcesRBACManager:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    extraEnvVarsCrossplane: {}
    extraEnvVarsRBACManager: {}
    podSecurityContextCrossplane: {}
    podSecurityContextRBACManager: {}
